set_property IOSTANDARD LVCMOS33 [get_ports {sys_LED_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_LED_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_LED_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_LED_o[0]}]
set_property PACKAGE_PIN M14 [get_ports {sys_LED_o[3]}]
set_property PACKAGE_PIN M15 [get_ports {sys_LED_o[2]}]
set_property PACKAGE_PIN G14 [get_ports {sys_LED_o[1]}]
set_property PACKAGE_PIN D18 [get_ports {sys_LED_o[0]}]
set_property PACKAGE_PIN L16 [get_ports sys_clk_i]
set_property PACKAGE_PIN G15 [get_ports sys_ena_i]
set_property PACKAGE_PIN P15 [get_ports sys_rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_ena_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_i]

set_property IOSTANDARD LVCMOS33 [get_ports i2s_sck_o]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_sd_i]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_ws_o]
set_property PACKAGE_PIN K18 [get_ports i2s_sck_o]
set_property PACKAGE_PIN K14 [get_ports i2s_sd_i]
set_property PACKAGE_PIN M18 [get_ports i2s_ws_o]


set_property IOSTANDARD LVCMOS33 [get_ports i2s_sck_i]
set_property IOSTANDARD LVCMOS33 [get_ports i2s_ws_i]
set_property PACKAGE_PIN V20 [get_ports i2s_sck_i]
set_property PACKAGE_PIN U20 [get_ports i2s_ws_i]
