# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/design_2.bd
# Block Designs: The module: 'design_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_top_0_0 || ORIG_REF_NAME==design_2_top_0_0} -quiet] -quiet

# XDC: C:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/design_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/design_2.bd
# Block Designs: The module: 'design_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_top_0_0 || ORIG_REF_NAME==design_2_top_0_0} -quiet] -quiet

# XDC: C:/Users/Owner/masterthesis4/masterthesis4.srcs/sources_1/bd/design_2/design_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2'. Do not add the DONT_TOUCH constraint.
